# Generated by Django 5.1.1 on 2024-12-03 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_alter_widget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layout.widget'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='cells',
            field=models.ManyToManyField(to='layout.cell'),
        ),
        migrations.AlterField(
            model_name='template',
            name='grids',
            field=models.ManyToManyField(to='layout.grid'),
        ),
    ]
